### ISSUE TITLE
Why is originalObject property needed in selectedObject?

### ISSUE THREAD

**Issue by ilya-khaustov** [ghiden/angucomplete-alt#122]
Hi, I use your directive in my project, it is awesome and I like it a lot. However I can't understand one special moment - when I define `selectedObject` attribute as one of my models, I can't use it directly, for example, to extract values from it in submit logic. All values I need are put in `originalObject` property which is inside `selectedObject`.
There is a workaround though - if I set `selectedObject` as a function, I can set my model to whatever I want using `originalObject` or anything else. But it looks a bit overcomplicated, shouldn't this be simpler?

**Comment by ghiden** [comment]
@ilya-khaustov This is basically historical reason. As you know, this is a fork of Angucomplete. Its goal is to show text, image, and description in a simple manner. Since I didn't want to drop the support of this feature, I kept it from the beginning when I started developing this -alt version. Personally, I only use originalObject all the time. Maybe you can create Angucomplete-Uber or something to make it simpler.
It's funny that you are asking for making it simpler but original intention I suppose was it is simple for dealing with text, image and description.

**Comment by pankas87** [comment]
I suggest may be adding a toString() method to the value object that when invoked returns originalObject.value

**Comment by YuniorGlez** [comment]
You can modify the angucomplete-alt.js code in line 170 (function callOrAssing(value) ) and modify this : 
          scope.selectedObject = value.originalObject;

      function callOrAssign(value) {
        if (typeof scope.selectedObject === 'function') {
          scope.selectedObject(value, scope.selectedObjectData);
        }
        else {
          scope.selectedObject = value.originalObject;
        }

        if (value) {
          handleRequired(true);
        }
        else {
          handleRequired(false);
        }
      }

**Comment by atul121001** [comment]
Some Edits to YuniorGlez code as error originalObject of undefined was coming

function callOrAssign(value) {
        if (typeof scope.selectedObject === 'function') {
          scope.selectedObject(value, scope.selectedObjectData);
        }
        else if(value) {
          scope.selectedObject = value.originalObject;
        }else{
          scope.selectedObject = value;
        }
        if (value) {
          handleRequired(true);
        }
        else {
          handleRequired(false);
        }
      }

**Comment by yuceldaglar** [comment]
I made these changes, you can find in https://github.com/yuceldaglar/angucomplete-alt 
Thanks.
