### ISSUE TITLE
on-focus: to start the input field as focused

### ISSUE THREAD

**Issue by ronaldogaraujo** [ghiden/angucomplete-alt#175]
Hi, 
Is it possible to bind ng-focus to angucomplete-alt?
I need  to start the input field as focused.

Thanks

**Comment by ghiden** [comment]
The easiest way is to use your custom template.
Only change that you need to make is add 'autofocus' to the input field like this.
http://plnkr.co/edit/ndbxRs?p=preview

**Comment by ronaldogaraujo** [comment]
thanks

**Comment by elifio** [comment]
I forked the plunker... In chrome works, but mozilla Iexplorer not :(

http://plnkr.co/edit/u5ddtI?p=preview

in theory works correctly in browsers (chrome = 5, iexplorer = 10, firefox = 4)
I'm using (chrome = 50., ieplorer=11, firefox=38)

**Comment by Boshen** [comment]
@elifio I suggest you to manually trigger the focus on the input, since the template is generated asynchronously, the browser may or may not trigger the focus for you.

**Comment by ManadayM** [comment]
I think setting `autofocus` on directive's template is not a perfect solution. In case of multiple instances/placements of the directive on a form, the last added element will get focus which is incorrect. 

I need similar behavior and was anticipating some boolean property like `input-autofocus` for the purpose. IMO, this would be more appropriate way because it'll prevent the case I just mentioned above. Please correct me if I'm wrong or missing something.
