### ISSUE TITLE
Is it possible to define required option (true/false) in $scope?

### ISSUE THREAD

**Issue by macgyver76** [ghiden/angucomplete-alt#184]
Hi again. Is it possible to set required option to variable in scope? Is it [bug](http://plnkr.co/edit/TpnbsQW7D7dXLAMOClrN?p=preview) or should be a new feature? 

I found out that while checking why is my form not valid. Previewing form's $error object in my project (not plunk above) I've discovered autocomplete-required array. Proof:

![image](https://cloud.githubusercontent.com/assets/9820004/8279910/9fff6b0e-18d8-11e5-9800-a74c9ce845ca.png)

I believe that's the reason of my form invalidity. With the possibility to set required option to false, I think my form would be valid then. Or am I missing something?

**Comment by ghiden** [comment]
fieldRequired is passed with @, so it is not 2-way-binding.
I don't even check if it says 'true' or not. As long as you provide something, it becomes true.
So, you can't toggle the required value.

**Comment by aganglada** [comment]
Hello @ghiden,

What does it means? Do you mind to fix it?

**Comment by ghiden** [comment]
@aganglada Do you need to toggle it? It's a breaking change so I probably won't change it.

**Comment by aganglada** [comment]
I think it is basic that inputs works as inputs everywhere, so required should work with the same behavior than a normal input.

I would consider to change it for the next version.

**Comment by ghiden** [comment]
@aganglada Thanks for your feedback. The implementation of required is a bit strange because it was impossible to add an input element from a child directive to the parent form controller on angular1.2. So I had to tweak the parent form controller rather than the input element's validity attribute. I'm planning to drop support of angular1.2 and that would simplify the implementation of required. If everything goes well, I should be able to make it 2-way bound.

**Comment by ghiden** [comment]
@aganglada Please have a look at this.
http://plnkr.co/edit/EDWfjY?p=preview
This is the new release candidate.

**Comment by aganglada** [comment]
Nice :) +1

**Comment by ghiden** [comment]
Released v2.0.0
