### ISSUE TITLE
Is there a reason you don't use ngModel?

### ISSUE THREAD

**Issue by mpolichette** [ghiden/angucomplete-alt#261]
ngModel provides a lot of features and allows external setting of some of the features you have implemented manually, for example, handling `required`, transforming or responses, using getters/setters, etc...

I am really liking this project and could probably be convinced to put the effort in to make some of the conversions.

Let me know if there is interest, or if there is a reason you've avoided it.
Thanks, you guys rock!

**Comment by ghiden** [comment]
Thanks for showing your interest.
This is a fork of angucomplete which started Jan/2014.
It was when angular was 1.2.
The original project started with not using ng-model.
I just followed that design.

Handling required is all manual because angular 1.2 did not allow dynamically adding a model to form controller. I think it's possible now with 1.4. I'm just keeping the backward compatibility.

And, I'm not planning to change the basic design.
I'm more like in maintenance mode.
If there is an bug, I'll fix it.

Now angular2 is coming, so I guess it's a good timing to start your own using ng-model.
