### ISSUE TITLE
text-no-results is shown when minlength is set to 0 and the search-string is empty

### ISSUE THREAD

**Issue by JaZo** [ghiden/angucomplete-alt#377]
text-no-results is shown when using remote-data, minlength is set to 0 and the search-string is empty. I see there is an if-condition for this case on [line 706](https://github.com/ghiden/angucomplete-alt/blob/v2.4.0/angucomplete-alt.js#L706), but I think the behavior is not correct since I would expect the text-searching to be shown.

**Comment by ghiden** [comment]
It makes sense that behaves like that.
But I guess it shouldn't behave like that.
I never liked this minlength=0 to show everything.
It was added due to popular demand. I guess it's mostly used for local data usage.
For remote api use cases, probably it doesn't make sense.
Usually search api doesn't return all when you send empty query string.
And, it totally varies how each API behaves, maybe return an error, maybe return empty set, maybe return all.
So, I think my best option would be just warn people not to use minlength=0 for remote api.

**Comment by JaZo** [comment]
Thanks for your quick reply! I am working on a PR for this and saw that I referred to the wrong line. I meant [line 638](https://github.com/ghiden/angucomplete-alt/blob/v2.4.0/angucomplete-alt.js#L638) instead. I created a [plunker](https://plnkr.co/edit/RRAGfCUaz5DBzxTcHzUh?p=preview) so you can see what I mean. When you focus the input-field, you will see the text-no-results for a short while before you get the actual results. I think this is confusing and it is better to show text-searching until the API results are back. When there are no results for the empty string, it can show text-no-results. In this [second plunker](https://plnkr.co/edit/N1nZsuaKO98j6hHeuU6C?p=preview), you can see the difference.

I think it is good to add a note to using minlength=0, but I would assume that the developer implementing this directive knows what the API will return in case of an empty string. I our case we have a dataset of approximately 50.000 results. When the user focusses the input field, we want to show the top 10 most popular results.
