### ISSUE TITLE
"selected-object" callback function called when typing

### ISSUE THREAD

**Issue by jlhffmn** [ghiden/angucomplete-alt#76]
I have a function specified for the "selected-object" attribute.  According to the documentation, it is only called when a "selection is made."  Sometimes the function is called when I first type a letter in the autocomplete entry box.  In this case, the argument to the function is "undefined".

**Comment by Ryaden** [comment]
I want to elaborate this issue a bit more. I've investigated it, to check when it actually happens.
Seems like it only happens when both "initial-value" and "selected-object" are set.

I've created this simple plunkr: http://plnkr.co/edit/GwDWptzp3KQLve0rb3FP
It'll log to the console whenever the callback is fired.

As you will see, everytime you type any character, it fires the callback.

If you remove, for example, the initial-value, the callback is not fired at every character.

**Comment by ghiden** [comment]
@Ryaden Thanks for reporting. I'll have a look.

**Comment by ghiden** [comment]
Actually it's the intended behavior.
Once object is set, it'll fire when it becomes undefined.
So, you need to have a guard-if statement.

**Comment by Ryaden** [comment]
Okay, thanks for checking! I'm completely fine with the guard-if statement.
