### ISSUE TITLE
Control is invalid when entering a value not from the result list

### ISSUE THREAD

**Issue by linstantnoodles** [ghiden/angucomplete-alt#97]
Inputs that are not part of the result list should be considered valid. Currently, I have my element set with the attribute `override-suggestions="true"` and yet any value that is not part of the result set still makes the control invalid. It doesn't look like the example for override on your site works either.

**Comment by peterjkirby** [comment]
I am having a similar issue. When overriding suggestions, a user is required to hit tab (it looks like key-down works too) in order to select their newly entered input value. If tab is not pushed then the form validity state never changes.

**Comment by ghiden** [comment]
Is it really not working? It looks like it's working. Hitting enter and tab does validate the field. 
http://plnkr.co/edit/hfPARQxPtd6PCgGas1iC?p=preview
But I figured that required and override suggestions do not work nicely since required expects user to select an item from the given list.

**Comment by peterjkirby** [comment]
I am using the required and override suggestions setting together because the field is required to be set prior to form submission and a user may create their own value if one of the dropdown options is not desired.

The tab/enter functionality does work as expected. My problem deals specifically with the case where a user does not hit tab/enter and instead uses their mouse (or finger if using a touch-enabled device) to focus out of the input area. In this specific case, form validation fails.

I would argue that expecting a user to hit tab/enter in order to validate an input field is probably asking too much of certain users :P

**Comment by ghiden** [comment]
@peterjkirby I got it. It makes sense. I'll check your code and probably merge it into master. Thanks.

**Comment by peterjkirby** [comment]
Great! Thanks!

**Comment by ghiden** [comment]
Fixed in v0.0.34.

**Comment by linstantnoodles** [comment]
@ghiden Thanks for adding the fix! However, this is creating a new problem. Now clicking a value from the auto complete drop down no longer populates the field. The user input is overriding the selection. 

For example:

If I type: "hello"

I get the following results:

"Hello world"
"Hello everyone"

If I click "Hello world", the field does *not* update toe "Hello world". Instead, it remains as "hello".

**Comment by ghiden** [comment]
Oh well, this is bad. I'll look into this. Thanks for reporting, @linstantnoodles

**Comment by linstantnoodles** [comment]
Cool! I made the same change on my local - didn't expect you to get to it so quickly. Thanks! Will let you know if this causes any issues.
